# Generated by Django 3.2.7 on 2021-09-16 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_auto_20210915_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('items_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=1000)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7, null=True)),
                ('purchased_items_obj', models.ManyToManyField(blank=True, to='bills.ItemPurchased')),
            ],
        ),
    ]
