# Generated by Django 3.2.7 on 2021-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210916_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchased',
            name='items_obj',
        ),
        migrations.AddField(
            model_name='itempurchased',
            name='product_name',
            field=models.CharField(default='item', max_length=1000),
        ),
        migrations.AddField(
            model_name='itempurchased',
            name='product_price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
