# Generated by Django 3.2.7 on 2021-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20210916_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchased_items_obj',
        ),
        migrations.AddField(
            model_name='customer',
            name='purchased_items_obj',
            field=models.ManyToManyField(blank=True, to='bills.ItemPurchased'),
        ),
    ]
