# Generated by Django 3.2.7 on 2021-09-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20210916_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchased_items_obj',
        ),
        migrations.AddField(
            model_name='itempurchased',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.customer'),
        ),
    ]
